FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o server ./cmd/api

FROM alpine:3.21
RUN apk add --no-cache ca-certificates tzdata curl
ENV TZ=Asia/Bangkok
WORKDIR /app
COPY --from=builder /app/server .
EXPOSE 3001
CMD ["./server"]
